/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.vistas;

import inventory.acceso.AccesoArchivo;
import inventory.acceso.AccesoExcepciones;
import inventory.acceso.AccesoLoggin;
import inventory.acceso.AccesoUsuario;
import inventory.objetos.ObjetosLoggin;
import inventory.objetos.ObjetosUsuario;
import java.io.IOException;
import java.util.ArrayList;

/**
 *
 * @author Megabytes Soluciones Integrales Guatemala
 */
public class wdwIngresoDeUsuario extends javax.swing.JInternalFrame {
    
    String UsuarioLogeado = null;
    AccesoUsuario Usuario = new AccesoUsuario();
    AccesoArchivo archivo = new AccesoArchivo();

    /**
     * Creates new form wdwIngresoDeUsuario
     */
    public wdwIngresoDeUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUsuario = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        lblClave = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setTitle("Ingreso de Usuario");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/logotipo.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(300, 200));
        setMinimumSize(new java.awt.Dimension(300, 200));
        setPreferredSize(new java.awt.Dimension(300, 200));

        pnlUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblUsuario.setText("Usuario");

        txtContrasenia.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Contraseña </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Ingrese la contraseña proporcionada por el administrador."
            + "</td></tr> <table> </html>");
        txtContrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraseniaKeyPressed(evt);
            }
        });

        txtUsuario.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Usuario </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/tooltip.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Ingrese el nombre de usuario, el sistema reconocera "
            + "tanto mayusculas como minusculas."
            + "</td></tr> <table> </html>");

        lblClave.setText("Clave");

        javax.swing.GroupLayout pnlUsuarioLayout = new javax.swing.GroupLayout(pnlUsuario);
        pnlUsuario.setLayout(pnlUsuarioLayout);
        pnlUsuarioLayout.setHorizontalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtContrasenia)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlUsuarioLayout.createSequentialGroup()
                        .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario)
                            .addComponent(lblClave))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlUsuarioLayout.setVerticalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblClave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/salir.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/eliminar_1.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 72, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAceptar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    AccesoExcepciones Mensaje = new AccesoExcepciones();
    ObjetosLoggin Loggin = new ObjetosLoggin();
    AccesoLoggin NuevoLoggin = new AccesoLoggin();
    public String vUsuario = null;

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtUsuario.setText("");
        txtContrasenia.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void comprobarUsuario() {

        ArrayList<ObjetosUsuario> usuarios = new ArrayList<>();
        AccesoUsuario acceso = new AccesoUsuario();
        usuarios = acceso.validaCredenciales(txtUsuario.getText(), txtContrasenia.getText());

        if (usuarios.size() == 0) {
            Mensaje.manipulacionExcepciones("critico", "El usurio y la contraseña son incorrectos");
        } else {
            if (usuarios.size() > 1) {
                Mensaje.manipulacionExcepciones("critico", "Exixte mas de un usuario con estas credenciales, verifique");
            } else {
                
                for (ObjetosUsuario x : usuarios) {
                    
                   
                    Inventory.lblUsuario.setText(x.getNombre_usuario());
                    Inventory.lblRol.setText(x.getTipo_usuario());
                    
                    System.err.println("TIPO USUARIO " + x.getTipo_usuario());
                    
                    if (x.getTipo_usuario().equals("Administrador")) {
                        Inventory.menu.setVisible(true);
                        Inventory.menuMovimiento.setVisible(true);
                        Inventory.menuCatalogo.setVisible(true);
                        Inventory.menuContabilidad.setVisible(true);
                        Inventory.menuReportes.setVisible(true);
                        Inventory.menuBaseDeDatos.setVisible(true);
                        Inventory.menuProveedores1.setVisible(true); // Menu Usuarios
                        this.dispose();
                    }

                    if (x.getTipo_usuario().equals("Jefe Sucursal")) {
                        Inventory.menu.setVisible(true);
                        Inventory.menuMovimiento.setVisible(true);
                        Inventory.menuAjusteInventario.setVisible(false);
                        Inventory.menuCatalogo.setVisible(true);
                        Inventory.menuEmpleados.setVisible(false);
                        Inventory.menuContabilidad.setVisible(false);
                        Inventory.menuReportes.setVisible(true);
                        Inventory.menuBaseDeDatos.setVisible(true);   
                        Inventory.menuProveedores1.setVisible(false); // Menu Usuarios
                        this.dispose();
                    }

                    if (x.getTipo_usuario().equals("Secretaria")) {
                        Inventory.menu.setVisible(true);
                        Inventory.menuMovimiento.setVisible(false);
                        Inventory.menuCatalogo.setVisible(true);
                        Inventory.menuContabilidad.setVisible(false);
                        Inventory.menuReportes.setVisible(true);
                        Inventory.menuBaseDeDatos.setVisible(false);
                        Inventory.menuAyuda.setVisible(true);
                        
                        // Items del menu movimientos
                        Inventory.menuCompraDeProductos.setVisible(false);
                        Inventory.menuVentaDeProductos.setVisible(false);
                        Inventory.menuProforma.setVisible(true);
                        Inventory.menuVentasActivas.setVisible(false);
                        Inventory.menuAnulacionVentas.setVisible(false);
                        Inventory.menuAbonoDeClientes.setVisible(false);
                        
                        //Items menu catalogos
                        Inventory.menuClientes.setVisible(true);
                        Inventory.menuProveedores.setVisible(true);
                        Inventory.menuProductos.setVisible(false);
                        Inventory.menuConsultaProductos.setVisible(true);
                        Inventory.menuProveedores1.setVisible(false); // Menu Usuarios
                        Inventory.menuSucursales.setVisible(false);
                        Inventory.menuEmpleados.setVisible(false);
                        Inventory.menuBonificaciones.setVisible(false);
                        Inventory.menuAjusteInventario.setVisible(false);
                        
                        this.dispose();
                    }

                    if (x.getTipo_usuario().equals("Cajero")) {
                        Inventory.menu.setVisible(true);
                        Inventory.menuMovimiento.setVisible(true);
                        Inventory.menuCatalogo.setVisible(false);
                        Inventory.menuContabilidad.setVisible(false);
                        Inventory.menuReportes.setVisible(false);
                        Inventory.menuBaseDeDatos.setVisible(false);
                        Inventory.menuAyuda.setVisible(true); 
                        
                        // Items del menu movimientos
                        Inventory.menuCompraDeProductos.setVisible(false);
                        Inventory.menuVentaDeProductos.setVisible(false);
                        Inventory.menuProforma.setVisible(true);
                        Inventory.menuVentasActivas.setVisible(true);
                        Inventory.menuAnulacionVentas.setVisible(true);
                        Inventory.menuAbonoDeClientes.setVisible(true);
                        Inventory.menuAjusteInventario.setVisible(false);
                        
                        //Items menu catalogos
                        Inventory.menuClientes.setVisible(true);
                        Inventory.menuProveedores.setVisible(false);
                        Inventory.menuProductos.setVisible(false);
                        Inventory.menuConsultaProductos.setVisible(true);
                        Inventory.menuProveedores1.setVisible(false); // Menu Usuarios
                        Inventory.menuSucursales.setVisible(false);
                        Inventory.menuEmpleados.setVisible(false);
                        Inventory.menuBonificaciones.setVisible(false);
                        
                        this.dispose();
                    }
                    
                    if (x.getTipo_usuario().equals("Vendedor")) {
                        
                        Inventory.menu.setVisible(true);
                        Inventory.menuMovimiento.setVisible(true);
                        Inventory.menuCatalogo.setVisible(true);
                        Inventory.menuContabilidad.setVisible(false);
                        Inventory.menuReportes.setVisible(false);
                        Inventory.menuBaseDeDatos.setVisible(true);
                        Inventory.menuAyuda.setVisible(true);
                        
                        // Items del menu movimientos
                        Inventory.menuCompraDeProductos.setVisible(false);
                        Inventory.menuVentaDeProductos.setVisible(true);
                        Inventory.menuProforma.setVisible(true);
                        Inventory.menuVentasActivas.setVisible(true);
                        Inventory.menuAnulacionVentas.setVisible(false);
                        Inventory.menuAbonoDeClientes.setVisible(false);
                        Inventory.menuAjusteInventario.setVisible(false);
                        
                        //Items menu catalogos
                        Inventory.menuClientes.setVisible(true);
                        Inventory.menuProveedores.setVisible(false);
                        Inventory.menuProductos.setVisible(true);
                        Inventory.menuConsultaProductos.setVisible(true);
                        Inventory.menuProveedores1.setVisible(false); // Menu Usuarios
                        Inventory.menuSucursales.setVisible(false);
                        Inventory.menuEmpleados.setVisible(false);
                        Inventory.menuBonificaciones.setVisible(false);
                        
                        this.dispose();
                    }
                    
                    if (x.getTipo_usuario().equals("Bodeguero")) {
                        
                        Inventory.menu.setVisible(true);
                        Inventory.menuMovimiento.setVisible(true);
                        Inventory.menuCatalogo.setVisible(true);
                        Inventory.menuContabilidad.setVisible(false);
                        Inventory.menuReportes.setVisible(false);
                        Inventory.menuBaseDeDatos.setVisible(true);
                        Inventory.menuAyuda.setVisible(true);
                        
                        // Items del menu movimientos
                        Inventory.menuCompraDeProductos.setVisible(true);
                        Inventory.menuVentaDeProductos.setVisible(false);
                        Inventory.menuProforma.setVisible(false);
                        Inventory.menuVentasActivas.setVisible(false);
                        Inventory.menuAnulacionVentas.setVisible(false);
                        Inventory.menuAbonoDeClientes.setVisible(false);
                        Inventory.menuAjusteInventario.setVisible(false);
                        
                        //Items menu catalogos
                        Inventory.menuClientes.setVisible(false);
                        Inventory.menuProveedores.setVisible(false);
                        Inventory.menuProductos.setVisible(false);
                        Inventory.menuConsultaProductos.setVisible(true);
                        Inventory.menuProveedores1.setVisible(false); // Menu Usuarios
                        Inventory.menuSucursales.setVisible(false);
                        Inventory.menuEmpleados.setVisible(false);
                        Inventory.menuBonificaciones.setVisible(false);
                        
                        this.dispose();
                    }
                    
                }
                
                //habilitar el modulo de contabilidad en el menu
                //esta opicon debe de activarse en el archivo de configuraciones
                try {
                    if(archivo.leer("[Conta]").equals("FALSE")){
                        Inventory.menuContabilidad.setVisible(false);
                    }
                } catch (IOException ex) {
                    System.out.println("Error al activar modulo contable");
                }
                
            }
        }
        
        txtContrasenia.setText("");
        txtUsuario.setText("");
        txtUsuario.requestFocus();
    }

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if(txtUsuario.getText().equals("megabytes") && txtContrasenia.getText().equals("Derwin2012mg")) {
            Inventory.menu.setVisible(true);
            Inventory.lblRol.setText("DBA");
            Inventory.lblUsuario.setText("Soporte");
            this.dispose();
        } else {
            Inventory.menuBaseDeDatosMantenimiento.setVisible(false);
            comprobarUsuario();
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtContraseniaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseniaKeyPressed
        if (evt.getKeyCode() == 10) {
            if (txtUsuario.getText().equals("megabytes") && txtContrasenia.getText().equals("Derwin2012mg")) {
                Inventory.menu.setVisible(true);
                Inventory.lblRol.setText("DBA");
                Inventory.lblUsuario.setText("Soporte");
                this.dispose();
            } else {
                Inventory.menuBaseDeDatosMantenimiento.setVisible(false);
                comprobarUsuario();
            }
        }
    }//GEN-LAST:event_txtContraseniaKeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlUsuario;
    private javax.swing.JPasswordField txtContrasenia;
    public static javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
