/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.vistas;

import inventory.acceso.*;
import inventory.objetos.ObjetosDetalleFactura;
import inventory.objetos.ObjetosFactura;
import inventory.servicios.Factura;
import inventory.servicios.Impresion;
import inventory.servicios.MaestroFactura;
import inventory.servicios.Producto;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Megabyte Soluciones Integrales Guatemala
 */


public class wdwMovimientoVentasActivas extends javax.swing.JInternalFrame {

    /**
     * Creates new form wdwBaseDeDAtosHistorialDeVentas
     */
    public wdwMovimientoVentasActivas() {
        initComponents();
        hilo p = new hilo("ordenes");
        p.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //VARIABLES GLOBALES
    AccesoFactura factura = new AccesoFactura();
    AccesoExcepciones mensaje = new AccesoExcepciones();
    AccesoArchivo archivo = new AccesoArchivo();
    
    private void mostrarVentasActivas(){
        
        DefaultTableModel tabla = new DefaultTableModel();
        ArrayList<ObjetosFactura> lista = new ArrayList();
        
        lista = factura.seleccionarFactura();
                
        if(!lista.isEmpty()){
            tabla.addColumn("Envio");
            tabla.addColumn("No. Factura");
            tabla.addColumn("Serie");
            tabla.addColumn("Folio");
            tabla.addColumn("Fecha");
            tabla.addColumn("monto_credito");
            tabla.addColumn("monto_contado");
            tabla.addColumn("Total");
            tabla.addColumn("Nombre");
            tabla.setRowCount(lista.size());
            int cFactura = 0;
            
            for (ObjetosFactura xFactura : lista) {
                tabla.setValueAt(xFactura.getId_factura(), cFactura, 0);
                tabla.setValueAt(xFactura.getNumero_factura(), cFactura, 1);
                tabla.setValueAt(xFactura.getSerie_factura(), cFactura, 2);
                tabla.setValueAt(xFactura.getFolio_factura(), cFactura, 3);
                tabla.setValueAt(xFactura.getFecha_emision_factura(), cFactura, 4);
                tabla.setValueAt(xFactura.getMonto_credito(), cFactura, 5);
                tabla.setValueAt(xFactura.getMonto_contado(), cFactura, 6);
                tabla.setValueAt(xFactura.getTotal_factura(), cFactura, 7);
                tabla.setValueAt(xFactura.getNombre_cliente(), cFactura, 8);
                cFactura++;
            }
            
            tblDetalleVenta.setModel(tabla);
        }
    }
    
    private class hilo implements Runnable {
        private Thread hilo;
        private String nombre;
        
        public hilo(String nombre){
            this.nombre = nombre;
            hilo = new Thread(this, "Hilo");
        }
        
        public void start(){
            hilo.start();
        }
        
        @Override
        public void run() {
            try {
                while(true){
                    if(nombre.equals("ordenes")){
                        mostrarVentasActivas();
                        Thread.sleep(5000);
                    }
                }
            } catch(InterruptedException e) {
                System.out.println("Error en ejecucion hilo");
            }
        }
        
    }
    
    public void restablecerTabla() {
        System.out.println("Se limpio el contenido de la tabla");
        for (int i=0; i<300; i++) {
            tblDetalleVenta.setValueAt(null, i, 0);
            tblDetalleVenta.setValueAt(null, i, 1);
            tblDetalleVenta.setValueAt(null, i, 2);
            tblDetalleVenta.setValueAt(null, i, 3);
            tblDetalleVenta.setValueAt(null, i, 4);
            tblDetalleVenta.setValueAt(null, i, 5);
            tblDetalleVenta.setValueAt(null, i, 6);
            tblDetalleVenta.setValueAt(null, i, 7);
        }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDetalle = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalleVenta = new javax.swing.JTable();
        pnlBotones = new javax.swing.JPanel();
        lblIdVenta = new javax.swing.JLabel();
        txtIdVenta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnReporte2 = new javax.swing.JButton();
        btnTicket = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ventas Activas");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/pantalla.png"))); // NOI18N

        pnlDetalle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblDetalleVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Venta", "Num. Factura", "Serie", "Folio", "Fecha", "Monto Credito", "Monto Contado", "Total", "Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDetalleVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetalleVentaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDetalleVenta);

        javax.swing.GroupLayout pnlDetalleLayout = new javax.swing.GroupLayout(pnlDetalle);
        pnlDetalle.setLayout(pnlDetalleLayout);
        pnlDetalleLayout.setHorizontalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDetalleLayout.setVerticalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblIdVenta.setText("Venta");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/money_v.png"))); // NOI18N
        jButton1.setText("Cobrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnReporte2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/impresora.png"))); // NOI18N
        btnReporte2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporte2ActionPerformed(evt);
            }
        });

        btnTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/invoice.png"))); // NOI18N
        btnTicket.setToolTipText("Imprimir Comprobante de pago");
        btnTicket.setActionCommand("imprimirEnvio");
        btnTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIdVenta)
                .addGap(18, 18, 18)
                .addComponent(txtIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReporte2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTicket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(btnTicket)
                    .addComponent(btnReporte2)
                    .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblIdVenta)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDetalle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDetalleVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetalleVentaMouseClicked
        if (String.valueOf(tblDetalleVenta.getSelectedColumn()).equals("0")) {   
            int fila_seleccionada = tblDetalleVenta.getSelectedRow();
            txtIdVenta.setText(tblDetalleVenta.getValueAt(fila_seleccionada, 0).toString());
        }
    }//GEN-LAST:event_tblDetalleVentaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AccesoFactura factura = new AccesoFactura();
        factura.cobrarFactura(txtIdVenta.getText());
        restablecerTabla();
        mostrarVentasActivas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnReporte2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporte2ActionPerformed

        try {
            AccesoInventario Acceso = new AccesoInventario();
            URL url_reporte = this.getClass().getResource("/inventory/reportes/rptEnvio.jasper");
            JasperReport reporte = (JasperReport) JRLoader.loadObject(url_reporte);
            //ENVIAR EL PARAMETRO AL REPORTES
            HashMap parametro = new HashMap();
            parametro.put("P_ID_FACTURA", Integer.parseInt(txtIdVenta.getText()));
            JasperPrint pantalla = JasperFillManager.fillReport(reporte, parametro, Acceso.conectar());
            JasperViewer visualizador = new JasperViewer(pantalla, false);
            visualizador.show();
        } catch (JRException error) {
            mensaje.manipulacionExcepciones("critico", "Ocurrio un error al ejecutar el reporte -> " + error);
        }
    }//GEN-LAST:event_btnReporte2ActionPerformed

    private void btnTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketActionPerformed
        //obtener el encabezado mediante el archivo de configuraciones
        String nombre = "";
        String direccion_uno = "";
        String direccion_dos = "";
        String telefono = "";
        try {
            nombre = archivo.leer("[name]");
            direccion_uno = archivo.leer("[adress]");
            direccion_dos = archivo.leer("[city]");
            telefono = archivo.leer("[phone]");
        } catch (IOException ex) {
            mensaje.manipulacionExcepciones("critico", "Ocurrio un error al ejecutar el reporte -> " + ex);
        }


        //Buscar el corelativo del recibo de pago
        int numero_correlativo = 0;
        AccesoFactura accesoFactura = new AccesoFactura();
        try {
            numero_correlativo = accesoFactura.retornaNumeroCorrelativo(txtIdVenta.getText());
        } catch (Exception exception) {
            System.out.println("Error al buscar el correlativo: " + exception.toString());
        }

        try {
            AccesoInventario Acceso = new AccesoInventario();
            URL url_reporte = this.getClass().getResource("/inventory/reportes/rptComprobante.jasper");
            JasperReport reporte = (JasperReport) JRLoader.loadObject(url_reporte);
            //ENVIAR EL PARAMETRO AL REPORTES
            HashMap parametro = new HashMap();
            parametro.put("P_ID_FACTURA", Integer.parseInt(txtIdVenta.getText()));
            parametro.put("P_EMPRESA", nombre);
            parametro.put("P_DIRECCION_UNO", direccion_uno);
            parametro.put("P_DIRECCION_DOS", direccion_dos);
            parametro.put("P_TELEFONO", telefono);
            parametro.put("P_CORRELATIVO", String.valueOf(numero_correlativo));
            JasperPrint pantalla = JasperFillManager.fillReport(reporte, parametro, Acceso.conectar());
            JasperViewer visualizador = new JasperViewer(pantalla, false);
            visualizador.show();
        } catch (JRException error) {
            mensaje.manipulacionExcepciones("critico", "Ocurrio un error al imprimir factura -> " + error);
        }
    }//GEN-LAST:event_btnTicketActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReporte2;
    private javax.swing.JButton btnTicket;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIdVenta;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDetalle;
    private javax.swing.JTable tblDetalleVenta;
    private javax.swing.JTextField txtIdVenta;
    // End of variables declaration//GEN-END:variables
}
